version: "3.9"

services:
  healthchecks:
    image: docker.io/healthchecks/healthchecks:v3.0.1@sha256:7d0c460264d48568c029a70575ac51c589e69485c7d971136ce923e46c30bf08
    container_name: healthchecks
    user: "${PUID}:${PGID}"
    volumes:
      - ./data:/data
    environment:
      - ALLOWED_HOSTS=${HEALTHCHECKS_HOST}
      - SITE_NAME=Healthchecks
      - REGISTRATION_OPEN=False
      - APPRISE_ENABLED=True
      - DB=sqlite
      - DB_NAME=/data/hc.sqlite
      - DEBUG=False
      - DEFAULT_FROM_EMAIL=${HEALTHCHECKS_DEFAULT_FROM_EMAIL}
      - EMAIL_HOST=${HEALTHCHECKS_EMAIL_HOST}
      - EMAIL_HOST_PASSWORD=${HEALTHCHECKS_EMAIL_HOST_PASSWORD}
      - EMAIL_HOST_USER=${HEALTHCHECKS_EMAIL_HOST_USER}
      - EMAIL_PORT=${HEALTHCHECKS_EMAIL_PORT}
      - EMAIL_USE_TLS=${HEALTHCHECKS_EMAIL_USE_TLS}
      - SECRET_KEY=${HEALTHCHECKS_SECRET_KEY}
      - SITE_ROOT=https://${HEALTHCHECKS_HOST}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.healthchecks.loadbalancer.server.port=8000"
      - "traefik.http.routers.healthchecks.service=healthchecks"
      - "traefik.http.routers.healthchecks.tls=true"
      - "traefik.http.routers.healthchecks.entrypoints=websecure"
      - 'traefik.http.routers.healthchecks.rule=Host("$HEALTHCHECKS_HOST")'
      - "traefik.http.routers.healthchecks.middlewares=authelia@docker"
    networks:
      - web_proxy
    # No healthcheck because no curl or wget

networks:
  web_proxy:
    external: true

