version: "3"

services:
  wallabagdb:
    image: linuxserver/mariadb:version-110.4.17mariabionic
    container_name: wallabagdb
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${WALLABAG_DB_ROOT_PASSWORD}
      - MYSQL_USER=wallabag
      - MYSQL_PASSWORD=${WALLABAG_DB_PASSWORD}
      - MYSQL_DATABASE=wallabag
    volumes:
      - ./db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - db

  wallabag:
    image: wallabag/wallabag
    container_name: wallabag
    depends_on:
      - wallabagdb
    environment:
      - SYMFONY__ENV__DOMAIN_NAME=${WALLABAG_URL}
      - SYMFONY__ENV__SECRET=${WALLABAG_SECRET}
      - SYMFONY__ENV__FOSUSER_REGISTRATION=false
      # Mail
      - SYMFONY__ENV__MAILER_HOST=${WALLABAG_MAIL_HOST}
      - SYMFONY__ENV__MAILER_USER=${WALLABAG_MAIL_USER}
      - SYMFONY__ENV__MAILER_PASSWORD=${WALLABAG_MAIL_PASSWORD}
      - SYMFONY__ENV__FROM_EMAIL=${WALLABAG_MAIL_FROM}
      # DB
      - POPULATE_DATABASE=false
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=wallabagdb
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=${WALLABAG_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${WALLABAG_DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./data:/var/www/wallabag/data
      - ./images:/var/www/wallabag/web/assets/images
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wallabag.service=wallabag"
      - "traefik.http.routers.wallabag.tls=true"
      - "traefik.http.routers.wallabag.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.wallabag.entrypoints=websecure"
      - "traefik.http.services.wallabag.loadbalancer.server.port=80"
    networks:
      - web_proxy
      - db

networks:
  web_proxy:
    external:
      name: web_proxy
  db:
    driver: bridge
