# To generate the auth file
# wget 'https://github.com/linx-server/linx-server/releases/download/v2.3.8/linx-genkey-v2.3.8_linux-amd64' -O linx-genkey
# chmod +x linx-genkey
# ./linx-genkey
# Enter key to hash: hello-world
# c0ctY9DXsRIXnZzYBUGnzoQBd5FY2E0Mvk6KtLLMJj4=
# echo c0ctY9DXsRIXnZzYBUGnzoQBd5FY2E0Mvk6KtLLMJj4= > auth
version: "3.9"

services:
  linx:
    image: andreimarcu/linx-server
    container_name: linx
    command: -config /data/linx.conf
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./files:/data/files
      - ./meta:/data/meta
      - ./linx.conf:/data/linx.conf
      - ./auth:/data/auth
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.linx.service=linx"
      - "traefik.http.routers.linx.tls=true"
      - "traefik.http.routers.linx.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.linx.entrypoints=websecure"
      - "traefik.http.services.linx.loadbalancer.server.port=8080"
    networks:
      - web_proxy

networks:
  web_proxy:
    external:
      name: web_proxy