version: "3.9"

services:
  sonarr:
    image: docker.io/linuxserver/sonarr:3.0.10@sha256:477e045901054ffac94a12e1fcaa0c05746a10df2d6ba761ec9fe18a992de4a2
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - ${SONARR_DOWNLOADS_PATH}:/downloads:rw,rslave
      - ${SONARR_TV_PATH}:/tv:rw,rslave
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.service=sonarr"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - 'traefik.http.routers.sonarr.rule=Host("$SONARR_HOST")'
      - "traefik.http.routers.sonarr.middlewares=authelia@docker"
    networks:
      - web_proxy
      - torrent

networks:
  web_proxy:
    external: true
  torrent:
    external: true
