version: "3.9"

services:
  sonarr:
    image: docker.io/linuxserver/sonarr:3.0.10@sha256:500af79ff1d83daee79143fd82d5d756bf0a33c048312a317a72ce747f62f0a9
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - ${SONARR_DOWNLOADS_PATH}:/downloads:rw,rslave
      - ${SONARR_TV_PATH}:/tv:rw,rslave
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.service=sonarr"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - 'traefik.http.routers.sonarr.rule=Host("$SONARR_HOST")'
      - "traefik.http.routers.sonarr.middlewares=authelia@docker"
    networks:
      - web_proxy
      - torrent

networks:
  web_proxy:
    external: true
  torrent:
    external: true
