version: "3.9"

services:
  multi_scrobbler:
    image: ghcr.io/foxxmd/multi-scrobbler:0.6.0@sha256:f7aa0eec72b17aae798cedf4ff3c2bfd77af3e8ff781aa394ed0126e8d0dbd9b
    container_name: multi_scrobbler
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MALOJA_API_KEY=${MALOJA_API_KEY}
      - MALOJA_URL=${MALOJA_URL}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
    volumes:
      - ./config:/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.multi_scrobbler.loadbalancer.server.port=9078"
      - "traefik.http.routers.multi_scrobbler.service=multi_scrobbler"
      - "traefik.http.routers.multi_scrobbler.tls=true"
      - "traefik.http.routers.multi_scrobbler.entrypoints=websecure"
      - 'traefik.http.routers.multi_scrobbler.rule=Host("$MULTI_SCROBBLER_HOST")'
      - "traefik.http.routers.multi_scrobbler.middlewares=authelia@docker"
    networks:
      - web_proxy
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:9078/api/status"]
      start_period: 20s
      interval: 30s
      timeout: 5s
      retries: 5

networks:
  web_proxy:
    external: true
