version: "3"

services:
  code-server:
    image: linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${CODE_SERVER_PASSWORD}
    volumes:
      - ./config:/config
      - /srv:/sources/srv
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code-server.service=code-server"
      - "traefik.http.routers.code-server.tls=true"
      - "traefik.http.routers.code-server.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.code-server.entrypoints=websecure"
      - "traefik.http.services.code-server.loadbalancer.server.port=8443"
    networks:
      - web_proxy

networks:
  web_proxy:
    external:
      name: web_proxy