version: "3.8"

services:
  # Clone https://github.com/standardnotes/syncing-server.git
  standardnotes-api:
    container_name: standardnotes-api
    user: "${PUID}:${PGID}"
    depends_on: 
      - standardnotesdb
    build: .
    command: start-local
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DISABLE_USER_REGISTRATION=true
      - DATADOG_ENABLED=false
      # DB
      - DB_HOST=standardnotesdb
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      # Mailer
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_DOMAIN=${SMTP_DOMAIN}
    volumes:
      - .:/syncing-server
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.standardnotes-api.service=standardnotes-api"
      - "traefik.http.routers.standardnotes-api.tls=true"
      - "traefik.http.routers.standardnotes-api.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.standardnotes-api.entrypoints=websecure"
      - "traefik.http.services.standardnotes-api.loadbalancer.server.port=3000"
    networks:
      - db
      - web_proxy

  standardnotes:
    container_name: standardnotes
    depends_on: 
      - standardnotesdb
      - standardnotes-api
    image: standardnotes/web:stable
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SF_DEFAULT_SERVER=http://standardnotes-api:3000
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.standardnotes.service=standardnotes"
      - "traefik.http.routers.standardnotes.tls=true"
      - "traefik.http.routers.standardnotes.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.standardnotes.entrypoints=websecure"
      - "traefik.http.services.standardnotes.loadbalancer.server.port=3000"
    networks:
      - web_proxy

  standardnotesdb:
    image: mysql:5.7
    container_name: standardnotesdb
    user: "${PUID}:${PGID}"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - db

networks:
  web_proxy:
    external:
      name: web_proxy
  db:
    driver: bridge
