version: "3.9"

services:
  prowlarr:
    image: docker.io/linuxserver/prowlarr:1.8.1259@sha256:76f6e8528e85ae295fcdc98e7b60f4a83cef2570ab13cd0e360fe4fd1cc21e43
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.service=prowlarr"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.routers.prowlarr.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.prowlarr.entrypoints=websecure"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      - 'traefik.http.routers.prowlarr.rule=Host("$PROWLARR_HOST")'
      - "traefik.http.routers.prowlarr.middlewares=authelia@docker"
    networks:
      - web_proxy
      - torrent

networks:
  web_proxy:
    external: true
  torrent:
    external: true
