version: "3"

services:
  projectsenddb:
    image: linuxserver/mariadb:version-110.4.17mariabionic
    container_name: projectsenddb
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${PROJECTSEND_ROOT_PASSWORD}
      - MYSQL_USER=projectsend
      - MYSQL_PASSWORD=${PROJECTSEND_DB_PASSWORD}
      - MYSQL_DATABASE=projectsend
    volumes:
      - ./db:/config
    restart: unless-stopped
    networks:
      - db

  projectsend:
    container_name: projectsend
    image: ghcr.io/linuxserver/projectsend
    restart: unless-stopped
    depends_on: 
      - projectsenddb
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./data:/data
      - ./config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.projectsend.service=projectsend"
      - "traefik.http.routers.projectsend.tls=true"
      - "traefik.http.routers.projectsend.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.projectsend.entrypoints=websecure"
      - "traefik.http.services.projectsend.loadbalancer.server.port=80"
    networks:
      - db
      - web_proxy

networks:
  web_proxy:
    external:
      name: web_proxy
  db:
    driver: bridge