version: "3"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    environment:
      - TZ=${TZ}
      - GENERIC_TIMEZONE=${TZ}
    volumes:
      - ./app:/root/.n8n
      - ./data:/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.service=n8n"
      - "traefik.http.routers.n8n.tls=true"
      - "traefik.http.routers.n8n.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.http.routers.n8n.middlewares=authelia@docker"
    networks:
      - web_proxy

networks:
  web_proxy:
    external:
      name: web_proxy