version: "3.9"

services:
  shlink_db:
    image: docker.io/library/postgres:15.4-alpine@sha256:7a92bbee4cee61c3ed58b1962c81e8aa3615ed01318aee1c48afc30d8ea8602e
    restart: unless-stopped
    container_name: shlink_db
    # See: https://github.com/docker-library/docs/blob/master/postgres/README.md#arbitrary---user-notes
    user: "${PUID}:${PGID}"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=shlink
      - POSTGRES_USER=shlink
      - POSTGRES_PASSWORD=${SHLINK_DB_PASSWORD}
    networks:
      - shlink
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s

  shlink_db_dumper:
    image: docker.io/paolobasso/database_dumper:postgres-15
    restart: unless-stopped
    depends_on:
      - shlink_db
    container_name: shlink_db_dumper
    volumes:
      - ./db_dumps:/dumps
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DUMPER_DATABASE=shlink
      - DUMPER_HOST=shlink_db
      - DUMPER_USER=shlink
      - DUMPER_PASSWORD=${SHLINK_DB_PASSWORD}
      - DUMPER_HEALTHCHECKS_URL=${SHLINK_DB_DUMPER_HEALTHCHECKS_URL}
    networks:
      - shlink

  shlink_client:
    image: docker.io/shlinkio/shlink-web-client:3.10.2@sha256:b96145d258f69e8c364d82a6a6f7278ddd472ead04b06f09b0d835bb9342e6af
    container_name: shlink_client
    depends_on:
      - shlink_db
      - shlink_server
    environment:
      - SHLINK_SERVER_URL=https://${SHLINK_SERVER_HOST}
      - SHLINK_SERVER_API_KEY=${SHLINK_SERVER_API_KEY}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shlink_client.service=shlink_client"
      - 'traefik.http.routers.shlink_client.rule=Host("$SHLINK_CLIENT_HOST")'
      - "traefik.http.routers.shlink_client.tls=true"
      - "traefik.http.routers.shlink_client.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.shlink_client.entrypoints=websecure"
      - "traefik.http.services.shlink_client.loadbalancer.server.port=80"
      - "traefik.http.routers.shlink_client.middlewares=authelia@docker"
    networks:
      - web_proxy

  shlink_server:
    image: docker.io/shlinkio/shlink:3.6.4-non-root@sha256:3c6ca9c9aec1ac98fd3ca61250d77e384a824326d4ecde688b1e521d593fc9da
    container_name: shlink_server
    depends_on:
      - shlink_db
    environment:
      - DEFAULT_DOMAIN=${SHLINK_SERVER_HOST}
      - IS_HTTPS_ENABLED=true
      - DEFAULT_BASE_URL_REDIRECT=${SHLINK_DEFAULT_BASE_URL_REDIRECT}
      - GEOLITE_LICENSE_KEY=${SHLINK_GEOLITE_LICENSE_KEY}
      - DB_DRIVER=postgres
      - DB_NAME=shlink
      - DB_USER=shlink
      - DB_PASSWORD=${SHLINK_DB_PASSWORD}
      - DB_HOST=shlink_db
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shlink_server.service=shlink_server"
      - 'traefik.http.routers.shlink_server.rule=Host("$SHLINK_SERVER_HOST")'
      - "traefik.http.routers.shlink_server.tls=true"
      - "traefik.http.routers.shlink_server.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.shlink_server.entrypoints=websecure"
      - "traefik.http.services.shlink_server.loadbalancer.server.port=8080"
    networks:
      - web_proxy
      - shlink

networks:
  web_proxy:
    external: true
  shlink:
    driver: bridge
