version: "3"

services:
  unbound:
    image: mvance/unbound
    container_name: unbound
    restart: unless-stopped
    networks:
      wireguard-pihole:
        ipv4_address: ${INTERNAL_NETWORK_SUBNET}.0.97

  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SERVERURL=${SERVERIP}
      - SERVERPORT=${WIREGUARD_SERVERPORT}
      - PEERS=${WIREGUARD_PEERS}
      - PEERDNS=${INTERNAL_NETWORK_SUBNET}.0.99
      - INTERNAL_SUBNET=${WIREGUARD_SUBNET}
    volumes:
      - ./wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - ${WIREGUARD_SERVERPORT}:51820/udp
    restart: unless-stopped
    networks:
      wireguard-pihole:
        ipv4_address: ${INTERNAL_NETWORK_SUBNET}.0.98

  pihole:
    image: pihole/pihole
    container_name: pihole
    depends_on:
      - unbound
    environment:
      - TZ=${TZ}
      - ServerIP=${SERVERIP}
      - WEBPASSWORD=${PIHOLE_PASSWORD}
      - DNS1=${INTERNAL_NETWORK_SUBNET}.0.97#53
      - DNS2=${INTERNAL_NETWORK_SUBNET}.0.97#53
    volumes:
      - ./pihole/config:/etc/pihole/
      - ./pihole/dnsmasq.d/:/etc/dnsmasq.d/
    dns: 
      - 127.0.0.1
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.service=pihole"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.routers.pihole.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    networks:
      web_proxy:
      wireguard-pihole:
        ipv4_address: ${INTERNAL_NETWORK_SUBNET}.0.99

networks:
  wireguard-pihole:
    driver: bridge
    ipam:
      config:
        - subnet: ${INTERNAL_NETWORK_SUBNET}.0.0/16
  web_proxy:
    external:
      name: web_proxy