version: "3"

services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    volumes:
      - /mnt:/srv/mnt
      - /home:/srv/home
      - ./config/filebrowser.db:/database.db
      - ./config/.filebrowser.json:/.filebrowser.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.service=filebrowser"
      - "traefik.http.routers.filebrowser.tls=true"
      - "traefik.http.routers.filebrowser.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.filebrowser.entrypoints=websecure"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"
    networks:
      - web_proxy

networks:
  web_proxy:
    external:
      name: web_proxy