version: "3"

services:
  statping:
    image: statping/statping
    container_name: statping
    volumes:
      - ./app:/app
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.statping.service=statping"
      - "traefik.http.routers.statping.tls=true"
      - "traefik.http.routers.statping.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.statping.entrypoints=websecure"
      - "traefik.http.services.statping.loadbalancer.server.port=8080"
    networks:
      - web_proxy

networks:
  web_proxy:
    external:
      name: web_proxy