version: "3.9"

services:
  authelia_redis:
    image: redis:6-alpine
    container_name: authelia_redis
    restart: unless-stopped
    networks:
      - authelia

  authelia_db:
    image: postgres:14
    restart: unless-stopped
    container_name: authelia_db
    user: "${PUID}:${PGID}"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=authelia
      - POSTGRES_USER=authelia
      - POSTGRES_PASSWORD=${AUTHELIA_STORAGE_POSTGRES_PASSWORD}
    networks:
      - authelia

  authelia_db_dumper:
    image: paolobasso/database_dumper:latest
    restart: unless-stopped
    depends_on:
      - authelia_db
    container_name: authelia_db_dumper
    volumes:
      - ./dumps:/dumps
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DUMPER_TYPE=postgres
      - DUMPER_DATABASE=authelia
      - DUMPER_HOST=authelia_db
      - DUMPER_USER=authelia
      - DUMPER_PASSWORD=${AUTHELIA_STORAGE_POSTGRES_PASSWORD}
      - DUMPER_HEALTHCHECKS_URL=${AUTHELIA_DB_DUMPER_HEALTHCHECKS_URL}
    networks:
      - authelia

  authelia:
    image: authelia/authelia:4
    depends_on:
      - authelia_redis
      - authelia_db
    container_name: authelia
    user: "${PUID}:${PGID}"
    restart: unless-stopped
    volumes:
      - ./config:/config
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - AUTHELIA_JWT_SECRET=${AUTHELIA_JWT_SECRET}
      # Session
      - AUTHELIA_SESSION_DOMAIN=${AUTHELIA_SESSION_DOMAIN}
      - AUTHELIA_SESSION_SECRET=${AUTHELIA_SESSION_SECRET}
      # Session: Redis
      - AUTHELIA_SESSION_REDIS_HOST=authelia_redis
      - AUTHELIA_SESSION_REDIS_PORT=6379
      # Database
      - AUTHELIA_STORAGE_ENCRYPTION_KEY=${AUTHELIA_STORAGE_ENCRYPTION_KEY}
      - AUTHELIA_STORAGE_POSTGRES_PASSWORD=${AUTHELIA_STORAGE_POSTGRES_PASSWORD}
      - AUTHELIA_STORAGE_POSTGRES_HOST=authelia_db
      - AUTHELIA_STORAGE_POSTGRES_PORT=5432
      - AUTHELIA_STORAGE_POSTGRES_DATABASE=authelia
      - AUTHELIA_STORAGE_POSTGRES_USERNAME=authelia
      - AUTHELIA_STORAGE_POSTGRES_SSLMODE=disable
      # Notifier
      - AUTHELIA_NOTIFIER_SMTP_USERNAME=${AUTHELIA_NOTIFIER_SMTP_USERNAME}
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD=${AUTHELIA_NOTIFIER_SMTP_PASSWORD}
      - AUTHELIA_NOTIFIER_SMTP_SENDER=${AUTHELIA_NOTIFIER_SMTP_SENDER}
      - AUTHELIA_NOTIFIER_SMTP_PORT=${AUTHELIA_NOTIFIER_SMTP_PORT}
      - AUTHELIA_NOTIFIER_SMTP_HOST=${AUTHELIA_NOTIFIER_SMTP_HOST}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.rule=Host(\"$AUTHELIA_HOST\")"
      - "traefik.http.routers.authelia.tls=true"
      - "traefik.http.routers.authelia.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.authelia.entrypoints=websecure"
      - "traefik.http.services.authelia.loadbalancer.server.port=9091"
      - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://$AUTHELIA_HOST"
      - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email"
      - "traefik.http.middlewares.authelia-basic.forwardauth.address=http://authelia:9091/api/verify?auth=basic"
      - "traefik.http.middlewares.authelia-basic.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia-basic.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email"
      # Authelia headers, see https://www.authelia.com/docs/security/measures.html#traefik-2x---docker-compose
      - "traefik.http.routers.authelia.middlewares=authelia-headers"
      - "traefik.http.middlewares.authelia-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.authelia-headers.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.authelia-headers.headers.customResponseHeaders.Cache-Control=no-store"
      - "traefik.http.middlewares.authelia-headers.headers.customResponseHeaders.Pragma=no-cache"
    networks:
      - web_proxy
      - authelia

networks:
  web_proxy:
    external: true
  authelia:
    driver: bridge
