version: "3.9"

services:
  bookstack_db:
    image: docker.io/linuxserver/mariadb:10.11.5@sha256:3902a03363609ab2eb6da63e7d8ba5514f2cecbb5b7e1064efb130a80993c820
    container_name: bookstack_db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${BOOKSTACK_DB_ROOT_PASSWORD}
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${BOOKSTACK_DB_PASSWORD}
      - MYSQL_DATABASE=bookstack
    volumes:
      - ./db:/config
    restart: unless-stopped
    networks:
      - bookstack

  bookstack_db_dumper:
    image: docker.io/paolobasso/database_dumper:mariadb
    restart: unless-stopped
    depends_on:
      - bookstack_db
    container_name: bookstack_db_dumper
    volumes:
      - ./db_dumps:/dumps
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DUMPER_DATABASE=bookstack
      - DUMPER_HOST=bookstack_db
      - DUMPER_USER=bookstack
      - DUMPER_PASSWORD=${BOOKSTACK_DB_PASSWORD}
      - DUMPER_HEALTHCHECKS_URL=${BOOKSTACK_DB_DUMPER_HEALTHCHECKS_URL}
    networks:
      - bookstack

  bookstack:
    image: docker.io/linuxserver/bookstack:23.08.3@sha256:dc813afc5c53ea36d176d51238a6e74555b0ba2ebcb27ecee9c858f337c5b143
    container_name: bookstack
    depends_on:
      - bookstack_db
    environment:
      - PUID=${PGID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=${BOOKSTACK_DB_PASSWORD}
      - DB_DATABASE=bookstack
      - APP_URL=https://${BOOKSTACK_HOST}
    volumes:
      - ./config:/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bookstack.service=bookstack"
      - "traefik.http.routers.bookstack.tls=true"
      - "traefik.http.routers.bookstack.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.bookstack.entrypoints=websecure"
      - 'traefik.http.routers.bookstack.rule=Host("$BOOKSTACK_HOST")'
      - "traefik.http.services.bookstack.loadbalancer.server.port=80"
    networks:
      - web_proxy
      - bookstack

networks:
  bookstack:
    driver: bridge
  web_proxy:
    external: true
