version: "3.9"

services:
  maloja:
    image: docker.io/krateng/maloja:3.2.1@sha256:5f73e1735a11bf5b7dd7921931091291f3bf6c2cf6679ae4b5f55d11a979c8db
    container_name: maloja
    user: ${PUID}:${PGID}
    environment:
      - MALOJA_DATA_DIRECTORY=/mljdata
      - MALOJA_FORCE_PASSWORD=${MALOJA_FORCE_PASSWORD}
    volumes:
      - ./data:/mljdata
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.maloja.loadbalancer.server.port=42010"
      - "traefik.http.routers.maloja.service=maloja"
      - "traefik.http.routers.maloja.tls=true"
      - "traefik.http.routers.maloja.entrypoints=websecure"
      - 'traefik.http.routers.maloja.rule=Host("$MALOJA_HOST")'
      - "traefik.http.routers.maloja.middlewares=authelia@docker"
    networks:
      - web_proxy
    # No healthcheck because no public endpoint

networks:
  web_proxy:
    external: true
