version: "3.9"

services:
  maloja:
    image: krateng/maloja
    container_name: maloja
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MALOJA_DATA_DIRECTORY=/mljdata
      - MALOJA_FORCE_PASSWORD=${MALOJA_FORCE_PASSWORD}
    volumes:
      - ./data:/mljdata
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.maloja.service=maloja"
      - "traefik.http.routers.maloja.tls=true"
      - "traefik.http.routers.maloja.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.maloja.entrypoints=websecure"
      - "traefik.http.services.maloja.loadbalancer.server.port=42010"
      - "traefik.http.routers.maloja.middlewares=authelia@docker"
    networks:
      - web_proxy

networks:
  web_proxy:
    external: true
