version: "3.9"

services:
  maloja:
    image: docker.io/krateng/maloja:3.1.5@sha256:2f6b746b37828e076988050c653e90b914154cfcd2d97d5ef96046fd66014dd6
    container_name: maloja
    user: ${PUID}:${PGID}
    environment:
      - MALOJA_DATA_DIRECTORY=/mljdata
      - MALOJA_FORCE_PASSWORD=${MALOJA_FORCE_PASSWORD}
    volumes:
      - ./data:/mljdata
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.maloja.loadbalancer.server.port=42010"
      - "traefik.http.routers.maloja.service=maloja"
      - "traefik.http.routers.maloja.tls=true"
      - "traefik.http.routers.maloja.entrypoints=websecure"
      - 'traefik.http.routers.maloja.rule=Host("$MALOJA_HOST")'
      - "traefik.http.routers.maloja.middlewares=authelia@docker"
    networks:
      - web_proxy

networks:
  web_proxy:
    external: true
