version: "3.9"

services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:6.0.2@sha256:02add40feae0569401b5020528e06419b47046723d0bb4bef1e82325e9eefdad
    container_name: recyclarr
    user: ${PUID}:${PGID}
    environment:
      - SONARR_API_KEY=${SONARR_API_KEY}
      - RADARR_API_KEY=${RADARR_API_KEY}
    volumes:
      - ./config:/config
    restart: unless-stopped
    networks:
      - torrent

networks:
  torrent:
    external: true
