version: "3.9"

services:
  navidrome:
    image: docker.io/deluan/navidrome:0.49.3@sha256:11a24da08977ebfa4a9a71f8c878d822ffaae74a019f274a75dc6386d523da86
    user: ${PUID}:${PGID}
    container_name: navidrome
    environment:
      - ND_SCANSCHEDULE=${NAVIDROME_SCANSCHEDULE}
      - ND_LOGLEVEL=${NAVIDROME_LOGLEVEL}
      - ND_SESSIONTIMEOUT=${NAVIDROME_SESSIONTIMEOUT}
      - ND_LISTENBRAINZ_BASEURL=${NAVIDROME_LISTENBRAINZ_BASEURL}
    volumes:
      - ./data:/data
      - ${NAVIDROME_MUSIC_PATH}:/music:ro,rslave
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.navidrome.service=navidrome"
      - "traefik.http.routers.navidrome.tls=true"
      - "traefik.http.routers.navidrome.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.navidrome.entrypoints=websecure"
      - "traefik.http.services.navidrome.loadbalancer.server.port=4533"
      - 'traefik.http.routers.navidrome.rule=Host("$NAVIDROME_HOST")'
      - "traefik.http.routers.navidrome.middlewares=authelia@docker"
    networks:
      - web_proxy

networks:
  web_proxy:
    external: true
