version: "3.9"

services:
  navidrome:
    image: docker.io/deluan/navidrome:0.54.2@sha256:d6b2288fb7311ce81e1eaa01e72f9c201c34893627b07e4813b4059dbb5a064d
    user: ${PUID}:${PGID}
    container_name: navidrome
    environment:
      - ND_SCANSCHEDULE=${NAVIDROME_SCANSCHEDULE}
      - ND_LOGLEVEL=${NAVIDROME_LOGLEVEL}
      - ND_SESSIONTIMEOUT=${NAVIDROME_SESSIONTIMEOUT}
      - ND_LISTENBRAINZ_BASEURL=${NAVIDROME_LISTENBRAINZ_BASEURL}
    volumes:
      - ./data:/data
      - ${NAVIDROME_MUSIC_PATH}:/music:ro,rslave
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.navidrome.loadbalancer.server.port=4533"
      - "traefik.http.routers.navidrome.service=navidrome"
      - "traefik.http.routers.navidrome.tls=true"
      - "traefik.http.routers.navidrome.entrypoints=websecure"
      - 'traefik.http.routers.navidrome.rule=Host("$NAVIDROME_HOST")'
      - "traefik.http.routers.navidrome.middlewares=authelia@docker"
    networks:
      - web_proxy
    # No healthcheck because already present in Dockerfile

networks:
  web_proxy:
    external: true
