version: "3"

services:
  traefik:
    container_name: traefik
    image: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme/acme.json:/acme.json
    networks:
      - web_proxy
    command:
      - --serversTransport.insecureSkipVerify=true
      # Global settings
      - --global.checkNewVersion=true
      - --global.sendAnonymousUsage=false
      # Entrypoints
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      # Dashboard
      - --api=true
      - --api.dashboard=true
      - --api.insecure=false
      - --api.debug=false
      # Log
      - --log=true
      - --log.level=WARN # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC
      # Certificate
#      - --certificatesResolvers.dns-cloudflare.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory # LetsEncrypt Staging Server
      - --certificatesResolvers.dns-cloudflare.acme.email=${CLOUDFLARE_EMAIL}
      - --certificatesResolvers.dns-cloudflare.acme.storage=/acme.json
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.provider=cloudflare
      # Docker provider
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=web_proxy
      - --providers.docker.swarmMode=false
      - --providers.docker.defaultRule=Host("{{ index .Labels "com.docker.compose.service" }}.$DOMAIN")
      # Metrics
      - --entryPoints.metrics.address=:5043
      - --metrics=true
      - --metrics.prometheus=true
      - --metrics.prometheus.entryPoint=metrics
      # Skip verification of backend certificates if needed, see https://community.containo.us/t/insecureskipverify-explanation/2195/28
#      - --serversTransport.insecureSkipVerify=true
    labels:
      - "traefik.enable=true"
      # Dashboard
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.rule=Host(\"$TRAEFIK_SUBDOMAIN.$DOMAIN\")"
      # Redirect http to https
      - "traefik.http.routers.http-catchall.rule=hostregexp(\"{host:.+}\")"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # Metrics
      - "traefik.http.routers.traefik-metrics.service=traefik-metrics"
      - "traefik.http.routers.traefik-metrics.tls=true"
      - "traefik.http.routers.traefik-metrics.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.traefik-metrics.entrypoints=websecure"
      - "traefik.http.services.traefik-metrics.loadbalancer.server.port=5043"
      - "traefik.http.routers.traefik-metrics.rule=Host(\"$TRAEFIK_SUBDOMAIN.$DOMAIN\") && Path(\"/metrics\")"
      # Basic auth
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-metrics.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=$TRAEFIK_USER_PASSWORD"

networks:
  web_proxy:
    external:
      name: web_proxy