---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options:

title: "Dashboard"
subtitle: "Homer"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: false
columns: 4

# Set the default layout and color scheme
defaults:
  layout: lists # Either 'columns', or 'list'
  colorTheme: auto # One of 'auto', 'light', or 'dark'

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
        - name: "Syncthing"
          target: "_blank"
          url: "https://syncthing.${HOMER_BASE_DOMAIN}"
          logo: "https://raw.githubusercontent.com/syncthing/syncthing/main/assets/logo-only.svg"
        - name: "Changedetection.io"
          url: "https://changedetection.${HOMER_BASE_DOMAIN}"
          target: "_blank"
          logo: "https://raw.githubusercontent.com/dgtlmoon/changedetection.io/master/changedetectionio/static/favicons/android-chrome-256x256.png"
        - name: "Shlink"
          url: "https://shlink.${HOMER_BASE_DOMAIN}"
          target: "_blank"
          logo: "https://shlink.io/images/shlink-logo-blue.svg"
        - name: "Paperless-ngx"
          url: "https://paperless-ngx.${HOMER_BASE_DOMAIN}"
          target: "_blank"
          logo: "https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/dev/src-ui/src/assets/logo-notext.svg"
        - name: "Gotify"
          url: "https://gotify.${HOMER_BASE_DOMAIN}"
          target: "_blank"
          logo: "https://raw.githubusercontent.com/gotify/logo/master/gotify-logo.png"
        - name: "Firefly III"
          url: "https://firefly.${HOMER_BASE_DOMAIN}"
          target: "_blank"
          logo: "https://docs.firefly-iii.org/firefly-iii/more-information/logo/logo.png"
        - name: "Bookstack"
          url: "https://bookstack.${HOMER_BASE_DOMAIN}"
          target: "_blank"
          logo: "https://upload.wikimedia.org/wikipedia/commons/d/d2/BookStack_logo.svg"
        - name: "Radicale"
          url: "https://radicale.${HOMER_BASE_DOMAIN}"
          target: "_blank"
          logo: "https://radicale.org/assets/logo.svg"
        - name: "Traefik"
          url: "https://traefik-hc01.${HOMER_BASE_DOMAIN}"
          target: "_blank"
          logo: "https://github.com/traefik/traefik/raw/master/docs/content/assets/img/traefik.logo-dark.png"
        - name: "Authelia"
          url: "https://authelia.${HOMER_BASE_DOMAIN}"
          target: "_blank"
          logo: "https://www.authelia.com/images/branding/logo-cropped.svg"
        - name: "Immich"
          url: "https://immich.${HOMER_BASE_DOMAIN}"
          logo: "https://github.com/immich-app/immich/raw/main/design/immich-logo.svg"
          target: "_blank"
        - name: "Prowlarr"
          url: "https://prowlarr.${HOMER_BASE_DOMAIN}"
          target: "_blank"
          logo: "https://raw.githubusercontent.com/Prowlarr/Prowlarr/develop/Logo/Prowlarr.svg"
        - name: "Sonarr"
          url: "https://sonarr.${HOMER_BASE_DOMAIN}"
          logo: "https://raw.githubusercontent.com/Sonarr/Sonarr/develop/Logo/Sonarr.svg"
          target: "_blank"
        - name: "Radarr"
          target: "_blank"
          url: "https://radarr.${HOMER_BASE_DOMAIN}"
          logo: "https://raw.githubusercontent.com/Radarr/Radarr/develop/Logo/Radarr.svg"
        - name: "Bazarr"
          url: "https://bazarr.${HOMER_BASE_DOMAIN}"
          target: "_blank"
          logo: "https://www.bazarr.media/assets/img/logo.png"
        - name: "Navidrome"
          url: "https://navidrome.${HOMER_BASE_DOMAIN}"
          target: "_blank"
          logo: "https://raw.githubusercontent.com/navidrome/navidrome/master/ui/public/android-chrome-512x512.png"
        - name: "Deluge"
          target: "_blank"
          url: "https://deluge.${HOMER_BASE_DOMAIN}"
          logo: "https://raw.githubusercontent.com/deluge-torrent/deluge/develop/deluge/ui/data/icons/hicolor/scalable/apps/deluge.svg"
        - name: "Jellyfin"
          url: "https://jellyfin.${HOMER_BASE_DOMAIN}"
          target: "_blank"
          logo: "https://raw.githubusercontent.com/jellyfin/jellyfin-ux/master/branding/SVG/icon-transparent.svg"
        - name: "Jellyseerr"
          url: "https://jellyseerr.${HOMER_BASE_DOMAIN}"
          target: "_blank"
          logo: "https://raw.githubusercontent.com/Fallenbagel/jellyseerr/develop/public/android-chrome-512x512.png"
        - name: "Maloja"
          url: "https://maloja.${HOMER_BASE_DOMAIN}"
          target: "_blank"
          logo: "https://raw.githubusercontent.com/krateng/maloja/master/maloja/web/static/png/favicon.png"
        - name: "Multi-scrobbler"
          url: "https://multi-scrobbler.${HOMER_BASE_DOMAIN}"
          target: "_blank"
          logo: "https://raw.githubusercontent.com/FoxxMD/multi-scrobbler/master/public/logo512.png"
        - name: "Jackett"
          url: "https://jackett.${HOMER_BASE_DOMAIN}"
          target: "_blank"
          logo: "https://avatars.githubusercontent.com/u/15383019"