version: "3.9"

services:
  radarr:
    image: docker.io/linuxserver/radarr:4.7.5@sha256:a7e8acff3f429351d2dfa1c887d751d13b8e974cd423841ed52be4203a4b1941
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - ${RADARR_DOWNLOADS_PATH}:/downloads:rw,rslave
      - ${RADARR_MOVIES_PATH}:/movies:rw,rslave
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.service=radarr"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - 'traefik.http.routers.radarr.rule=Host("$RADARR_HOST")'
      - "traefik.http.routers.radarr.middlewares=authelia@docker"
    networks:
      - web_proxy
      - torrent

networks:
  web_proxy:
    external: true
  torrent:
    external: true
