version: '3'

services:
  home-assistant:
    image: homeassistant/home-assistant:stable
    container_name: home-assistant
    restart: unless-stopped
    volumes:
     - ./config:/config
     - /etc/localtime:/etc/localtime:ro
    ports:
     - 8123:8123