version: "3.9"

services:
  paperless_ngx_redis:
    image: docker.io/library/redis:7.2.1-alpine@sha256:343e6546f35877801de0b8580274a5e3a8e8464cabe545a2dd9f3c78df77542a
    container_name: paperless_ngx_redis
    restart: unless-stopped
    networks:
      - paperless_ngx
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s

  paperless_ngx_db:
    image: docker.io/library/postgres:15.4-alpine@sha256:7a92bbee4cee61c3ed58b1962c81e8aa3615ed01318aee1c48afc30d8ea8602e
    restart: unless-stopped
    container_name: papeless_ngx_db
    # See: https://github.com/docker-library/docs/blob/master/postgres/README.md#arbitrary---user-notes
    user: "${PUID}:${PGID}"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=paperless_ngx
      - POSTGRES_USER=paperless_ngx
      - POSTGRES_PASSWORD=${PAPERLESS_NGX_DB_PASSWORD}
    networks:
      - paperless_ngx
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s

  paperless_ngx_db_dumper:
    image: docker.io/paolobasso/database_dumper:postgres-15
    restart: unless-stopped
    depends_on:
      - paperless_ngx_db
    container_name: paperless_ngx_db_dumper
    volumes:
      - ./db_dumps:/dumps
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DUMPER_DATABASE=paperless_ngx
      - DUMPER_HOST=paperless_ngx_db
      - DUMPER_USER=paperless_ngx
      - DUMPER_PASSWORD=${PAPERLESS_NGX_DB_PASSWORD}
      - DUMPER_HEALTHCHECKS_URL=${PAPERLESS_NGX_DB_DUMPER_HEALTHCHECKS_URL}
    networks:
      - paperless_ngx

  paperless_ngx_tika:
    image: ghcr.io/paperless-ngx/tika@sha256:b6154c8778cf6fd8ca46ba96f25846241ffdb12d033b578f8cd85893734eb155
    container_name: paperless_ngx_tika
    restart: unless-stopped
    user: ${PUID}:${PGID}
    networks:
      - paperless_ngx
    # No healthcheck because no curl or wget

  paperless_ngx_gotenberg:
    image: docker.io/gotenberg/gotenberg:7.9.2@sha256:2e4fcccf5e065bf4d92b0b69c80776505e602dbfb11618c1c4e4e8be8a0630e9
    restart: unless-stopped
    container_name: paperless_ngx_gotenberg
    user: ${PUID}:${PGID}
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:3000/health"]
      start_period: 20s
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - paperless_ngx

  paperless_ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:1.17.4@sha256:2daa90449bc5a57ce6b58792f873f0da6d09039b74caa9f89e28010e40ef770e
    container_name: paperless_ngx
    depends_on:
      - paperless_ngx_redis
      - paperless_ngx_db
      - paperless_ngx_tika
      - paperless_ngx_gotenberg
    environment:
      - USERMAP_UID=${PUID}
      - USERMAP_GID=${PGID}
      - PAPERLESS_TIME_ZONE=${TZ}
      - PAPERLESS_SECRET_KEY=${PAPERLESS_NGX_SECRET_KEY}
      - PAPERLESS_OCR_LANGUAGE=${PAPERLESS_NGX_OCR_LANGUAGE}
      - PAPERLESS_REDIS=redis://paperless_ngx_redis:6379
      - PAPERLESS_DBHOST=paperless_ngx_db
      - PAPERLESS_DBPORT=5432
      - PAPERLESS_DBUSER=paperless_ngx
      - PAPERLESS_DBNAME=paperless_ngx
      - PAPERLESS_DBPASS=${PAPERLESS_NGX_DB_PASSWORD}
      - PAPERLESS_TIKA_ENABLED=1
      - PAPERLESS_TIKA_GOTENBERG_ENDPOINT=http://paperless_ngx_gotenberg:3000
      - PAPERLESS_TIKA_ENDPOINT=http://paperless_ngx_tika:9998
      - PAPERLESS_URL=https://${PAPERLESS_NGX_HOST}
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.paperless_ngx.loadbalancer.server.port=8000"
      - "traefik.http.routers.paperless_ngx.service=paperless_ngx"
      - "traefik.http.routers.paperless_ngx.tls=true"
      - "traefik.http.routers.paperless_ngx.entrypoints=websecure"
      - 'traefik.http.routers.paperless_ngx.rule=Host("$PAPERLESS_NGX_HOST")'
      - "traefik.http.routers.paperless_ngx.middlewares=authelia@docker"
    networks:
      - paperless_ngx
      - web_proxy
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      start_period: 20s
      interval: 30s
      timeout: 5s
      retries: 5

  paperless_ngx_webdav:
    image: docker.io/paolobasso/webdav
    container_name: paperless_ngx_webdav
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./consume:/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.paperless_ngx_webdav.loadbalancer.server.port=80"
      - "traefik.http.routers.paperless_ngx_webdav.service=paperless_ngx_webdav"
      - "traefik.http.routers.paperless_ngx_webdav.tls=true"
      - "traefik.http.routers.paperless_ngx_webdav.entrypoints=websecure"
      - "traefik.http.routers.paperless_ngx_webdav.middlewares=authelia-basic@docker"
      - 'traefik.http.routers.paperless_ngx_webdav.rule=Host("$PAPERLESS_NGX_WEBDAV_HOST")'
    networks:
      - web_proxy
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:80"]
      start_period: 20s
      interval: 30s
      timeout: 5s
      retries: 5

networks:
  web_proxy:
    external: true
  paperless_ngx:
    driver: bridge
