version: "3"

services:
  psitransfer:
    image: psitrax/psitransfer
    container_name: psitransfer
    user: "${PUID}:${PGID}"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PSITRANSFER_ADMIN_PASS=${PSITRANSFER_PASSWORD}
    volumes:
      - ./data:/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.psitransfer.service=psitransfer"
      - "traefik.http.routers.psitransfer.tls=true"
      - "traefik.http.routers.psitransfer.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.psitransfer.entrypoints=websecure"
      - "traefik.http.services.psitransfer.loadbalancer.server.port=3000"
      - "traefik.http.routers.psitransfer.middlewares=authelia@docker"
    networks:
      - web_proxy

networks:
  web_proxy:
    external:
      name: web_proxy