version: "3.9"

services:
  radicale:
    image: docker.io/tomsquest/docker-radicale:3.1.8.3@sha256:b5dac16dafcb003520a1ea95d3e25a24d0955cc552b0d6d447163f0e070780ff
    container_name: radicale
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - KILL
    security_opt:
      - no-new-privileges:true
    init: true
    read_only: true
    restart: unless-stopped
    volumes:
      - ./config:/config:ro
      - ./data:/data
    environment:
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.radicale.loadbalancer.server.port=5232"
      - "traefik.http.routers.radicale.service=radicale"
      - "traefik.http.routers.radicale.tls=true"
      - "traefik.http.routers.radicale.entrypoints=websecure"
      - 'traefik.http.routers.radicale.rule=Host("$RADICALE_HOST")'
    networks:
      - web_proxy
    healthcheck:
      test: curl -f http://127.0.0.1:5232 || exit 1
      interval: 30s
      retries: 3

networks:
  web_proxy:
    external: true
