version: "3"

services:
  papermerge:
    image: linuxserver/papermerge
    container_name: papermerge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:papermerge-multilangocr
      - OCRLANG=ita
    volumes:
      - ./config:/config
      - ./data:/data
      - ./webdav:/import
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.papermerge.service=papermerge"
      - "traefik.http.routers.papermerge.tls=true"
      - "traefik.http.routers.papermerge.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.papermerge.entrypoints=websecure"
      - "traefik.http.services.papermerge.loadbalancer.server.port=8000"
      - "traefik.http.routers.papermerge.middlewares=authelia@docker"
    networks:
      - web_proxy

  papermerge-webdav:
    image: paolobasso/webdav
    container_name: papermerge-webdav
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./webdav:/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.papermerge-webdav.service=papermerge-webdav"
      - "traefik.http.routers.papermerge-webdav.tls=true"
      - "traefik.http.routers.papermerge-webdav.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.papermerge-webdav.entrypoints=websecure"
      - "traefik.http.services.papermerge-webdav.loadbalancer.server.port=80"
      - "traefik.http.routers.papermerge-webdav.middlewares=authelia-basic@docker"
    networks:
      - web_proxy

networks:
  web_proxy:
    external:
      name: web_proxy