version: "3.7"

services:
  searx:
    image: searx/searx:latest
    container_name: searx
    command: -f
    environment:
      - BIND_ADDRESS=0.0.0.0:8080
      - BASE_URL=https://${SEARX_HOSTNAME}/
      - MORTY_URL=https://${MORTY_HOSTNAME}/
      - MORTY_KEY=${MORTY_KEY}
    volumes:
      - ./config:/etc/searx:rw
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.searx.service=searx"
      - "traefik.http.routers.searx.tls=true"
      - "traefik.http.routers.searx.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.searx.entrypoints=websecure"
      - "traefik.http.services.searx.loadbalancer.server.port=8080"
      # Basic auth
      - "traefik.http.routers.searx.middlewares=searx-auth"
      - "traefik.http.middlewares.searx-auth.basicauth.users=$SEARX_USER_PASSWORD"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    networks:
      - web_proxy

  morty:
    container_name: morty
    image: dalf/morty
    restart: unless-stopped
    networks:
      - web_proxy
    command: -timeout 6 -ipv6 -socks5 ${MORTY_SOCKS5_USERNAME}:${MORTY_SOCKS5_PASSWORD}@${MORTY_SOCKS5_HOST}:${MORTY_SOCKS5_PORT}
    environment:
      - MORTY_KEY=${MORTY_KEY}
      - MORTY_ADDRESS=0.0.0.0:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.morty.service=morty"
      - "traefik.http.routers.morty.tls=true"
      - "traefik.http.routers.morty.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.morty.entrypoints=websecure"
      - "traefik.http.services.morty.loadbalancer.server.port=3000"
      # Basic auth
      - "traefik.http.routers.morty.middlewares=morty-auth"
      - "traefik.http.middlewares.morty-auth.basicauth.users=$SEARX_USER_PASSWORD"
    read_only: true
    cap_drop:
      - ALL

networks:
  web_proxy:
    external:
      name: web_proxy
