version: "3.7"

services: 
    jackett:
        image: linuxserver/jackett
        container_name: jackett
        environment:
          - PUID=${PUID}
          - PGID=${PGID}
          - TZ=${TZ}
        volumes:
          - ./config:/config
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.jackett.service=jackett"
            - "traefik.http.routers.jackett.tls=true"
            - "traefik.http.routers.jackett.tls.certresolver=dns-cloudflare"
            - "traefik.http.routers.jackett.entrypoints=websecure"
            - "traefik.http.services.jackett.loadbalancer.server.port=9117"
            - "traefik.http.routers.jackett.middlewares=authelia@docker"
        networks:
          - web_proxy

networks:
    web_proxy:
        external:
            name: web_proxy
