version: "3.9"

services:
  homer:
    image: docker.io/b4bz/homer:v24.12.1@sha256:4b44a4a9e3294ccef756275271342661c389ae2936e71ac96b911a139de57757
    container_name: homer
    volumes:
      - ./assets:/www/assets
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.homer.loadbalancer.server.port=8080"
      - "traefik.http.routers.homer.service=homer"
      - "traefik.http.routers.homer.tls=true"
      - "traefik.http.routers.homer.entrypoints=websecure"
      - 'traefik.http.routers.homer.rule=Host("$HOMER_HOST")'
      - "traefik.http.routers.homer.middlewares=authelia@docker"
    networks:
      - web_proxy
    # No healthchek because already present in Dockerfile

networks:
  web_proxy:
    external: true
