# https://github.com/searxng/searxng/blob/master/searx/settings.yml
use_default_settings: true

server:
  secret_key: "ultrasecretkey" # change this!
  limiter: false
  image_proxy: true

ui:
  static_use_hash: true

redis:
  url: redis://searxng_redis:6379/0

engines:
  - name: prowlarr.bassopaolo.com
    engine: torznab
    shortcut: prw
    base_url: http://jackett:9117/api/v2.0/indexers/all/results/torznab
    enable_http: true
    timeout: 10.0
    api_key: 6fd318df0bd64d24a0efc0662ebf5b87
