version: "3.9"

services:
  deluge:
    image: docker.io/binhex/arch-delugevpn:2.1.1-4-04@sha256:d23477a27d878cfaa2572ff771b45921bf0786ba4eefff5f3aab340948535a85
    container_name: deluge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=000
      - TZ=${TZ}
      - VPN_ENABLED=yes
      - VPN_PROV=custom
      - VPN_CLIENT=openvpn
      - VPN_USER=${DELUGE_VPN_USER}
      - VPN_PASS=${DELUGE_VPN_PASS}
      - ENABLE_PRIVOXY=no
      - LAN_NETWORK=192.168.1.0/24
      - NAME_SERVERS=84.200.69.80,37.235.1.174,1.1.1.1,37.235.1.177,84.200.70.40,1.0.0.1
      - DELUGE_DAEMON_LOG_LEVEL=info
      - DELUGE_WEB_LOG_LEVEL=info
      - DELUGE_ENABLE_WEBUI_PASSWORD=yes
      - DEBUG=false
    volumes:
      - ./config:/config
      - ${DELUGE_DOWNLOADS_PATH}:/downloads:rw,rslave
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    cap_add:
      - "NET_ADMIN"
    networks:
      - torrent

  deluge_proxy:
    image: docker.io/library/caddy:2.7.4-alpine@sha256:3d1bf053476f2415b40e728c37e1112ee7551fa154a63d6f62b275c13fea8166
    restart: unless-stopped
    container_name: deluge_proxy
    command: caddy reverse-proxy --from :80 --to deluge:8112
    user: "${PUID}:${PGID}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deluge_proxy.service=deluge_proxy"
      - 'traefik.http.routers.deluge_proxy.rule=Host("${DELUGE_HOST}")'
      - "traefik.http.routers.deluge_proxy.tls=true"
      - "traefik.http.routers.deluge_proxy.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.deluge_proxy.entrypoints=websecure"
      - "traefik.http.services.deluge_proxy.loadbalancer.server.port=80"
      - "traefik.http.routers.deluge_proxy.middlewares=authelia@docker"
    networks:
      - torrent
      - web_proxy

networks:
  web_proxy:
    external: true
  torrent:
    external: true

