version: "3.9"

services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin:10.11.1@sha256:c7dd335d455c95ad3fe7550824d93ceb911914bf4210e7899e11f9611ae53a92
    container_name: jellyfin
    user: ${PUID}:${PGID}
    environment:
      - JELLYFIN_PublishedServerUrl=https://${JELLYFIN_HOST}
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ${JELLYFIN_MOVIES_PATH}:/movies:rw,rslave
      - ${JELLYFIN_TV_PATH}:/tv:rw,rslave
      - ${JELLYFIN_MUSIC_PATH}:/music:rw,rslave
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.http.routers.jellyfin.service=jellyfin"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - 'traefik.http.routers.jellyfin.rule=Host("$JELLYFIN_HOST")'
    #      - "traefik.http.routers.jellyfin.middlewares=authelia@docker"
    networks:
      - web_proxy
      - torrent
    # No healthcheck because already present in Dockerfile

networks:
  web_proxy:
    external: true
  torrent:
    external: true
