version: '3'

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./data:/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.middlewares=authelia@docker"
    networks:
      - web_proxy

networks:
  web_proxy:
    external:
      name: web_proxy