###############################################################
#                   Authelia configuration                    #
###############################################################

theme: dark

server:
  host: 0.0.0.0
  port: 9091

log:
  level: warn

default_redirection_url: https://authelia.bassopaolo.com

totp:
  issuer: authelia.com
  period: 30
  skew: 1

ntp:
  address: "time.cloudflare.com:123"
  version: 4
  max_desync: 3s
  disable_startup_check: false
  disable_failure: false

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 1024 # blocks this much of the RAM. Tune this.

access_control:
  default_policy: deny
  rules:
    - domain: authelia.bassopaolo.com
      policy: bypass

    - domain:
        - traefik-hc01.bassopaolo.com
        - monitoring-hc01.bassopaolo.com
      policy: one_factor
      resources:
        # Match url that ends with "/metrics" and "/metrics/"
        - "^/?.*/metrics/?$"
      subject:
        - user:prometheus

    - domain:
        - syncthing-webdav.bassopaolo.com
        - paperless-ng-webdav.bassopaolo.com
      policy: one_factor
      subject:
        - group:admins
        - user:webdav

    - domain:
        - monicahq.bassopaolo.com
      policy: bypass
      resources:
        # Match url that starts with "/dav"
        - "^/dav.*$"

    - domain:
        - loki.bassopaolo.com
      policy: one_factor
      resources:
        # Match url that starts with "/loki/api"
        - "^/loki/api.*$"
      subject:
        - user:promtail-hc01

    - domain:
        - "*.bassopaolo.com"
        - "bassopaolo.com"
      policy: two_factor
      subject:
        - group:admins

session:
  name: authelia_session
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: bassopaolo.com # Should match whatever your root protected domain is

  redis:
    host: authelia_redis
    port: 6379

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  postgres:
    host: authelia_db
    port: 5432
    database: authelia
    username: authelia
    sslmode: disable

notifier:
  smtp:
    username: authelia@mail.bassopaolo.com
    host: smtp.eu.mailgun.org
    port: 25
    sender: authelia@bassopaolo.com