# Create passwords with: docker run authelia/authelia:latest authelia hash-password YOUR_PASSWORD

users:
  admin_user_name:
    displayname: "Name"
    password: HASHED_PASSWORD
    email: myemail@domain.com
    groups:
      - admins

  webdav:
    displayname: "WebDAV"
    password: HASHED_PASSWORD
    email: webdav-user@domain.com
    groups:
      - webdav

  promeheus:
    displayname: "Prometheus"
    password: HASHED_PASSWORD
    email: prometheus@domain.com

  promtail-servername:
    displayname: "Promtail Servername"
    password: HASHED_PASSWORD
    email: promtail-servername@domain.com