version: "3.9"

services:
  bazarr:
    image: docker.io/linuxserver/bazarr:1.3.0@sha256:48498977e457a3b5b9134e29ae83c70caa18a2c07828942c1b2d2c381f7d4b26
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - ${BAZARR_MOVIES_PATH}:/movies:rw,rslave
      - ${BAZARR_TV_PATH}:/tv:rw,rslave
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
      - "traefik.http.routers.bazarr.service=bazarr"
      - "traefik.http.routers.bazarr.tls=true"
      - "traefik.http.routers.bazarr.entrypoints=websecure"
      - 'traefik.http.routers.bazarr.rule=Host("$BAZARR_HOST")'
      - "traefik.http.routers.bazarr.middlewares=authelia@docker"
    networks:
      - web_proxy
      - torrent

networks:
  web_proxy:
    external: true
  torrent:
    external: true
