version: "3.9"

services:
  bazarr:
    image: docker.io/linuxserver/bazarr:1.3.0@sha256:99aa02543dee5c896ea1b95e952a01331e822975cbd4c234fb20ef447b591c66
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - ${BAZARR_MOVIES_PATH}:/movies:rw,rslave
      - ${BAZARR_TV_PATH}:/tv:rw,rslave
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.service=bazarr"
      - "traefik.http.routers.bazarr.tls=true"
      - "traefik.http.routers.bazarr.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.bazarr.entrypoints=websecure"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
      - 'traefik.http.routers.bazarr.rule=Host("$BAZARR_HOST")'
      - "traefik.http.routers.bazarr.middlewares=authelia@docker"
    networks:
      - web_proxy
      - torrent

networks:
  web_proxy:
    external: true
  torrent:
    external: true
