version: "3.9"

services:
  traggo:
    container_name: traggo
    image: traggo/server:latest
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TRAGGO_DEFAULT_USER_NAME=${TRAGGO_USERNAME}
      - TRAGGO_DEFAULT_USER_PASS=${TRAGGO_PASSWORD}
    volumes:
      - ./data:/opt/traggo/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traggo.service=traggo"
      - "traefik.http.routers.traggo.tls=true"
      - "traefik.http.routers.traggo.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.traggo.entrypoints=websecure"
      - "traefik.http.services.traggo.loadbalancer.server.port=3030"
      - "traefik.http.routers.traggo.middlewares=authelia@docker"
    networks:
      - web_proxy

networks:
  web_proxy:
    external:
      name: web_proxy