version: "3"

services:
  ubooquity:
    image: ghcr.io/linuxserver/ubooquity
    container_name: ubooquity
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - ./data/books:/books:rw,rslave
      - ./data/comics:/comics:rw,rslave
      - ./data/files:/files:rw,rslave
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # Library
      - "traefik.http.routers.ubooquity-library.service=ubooquity-library"
      - 'traefik.http.routers.ubooquity-library.rule=Host("ubooquity.$DOMAIN")'
      - "traefik.http.routers.ubooquity-library.tls=true"
      - "traefik.http.routers.ubooquity-library.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.ubooquity-library.entrypoints=websecure"
      - "traefik.http.services.ubooquity-library.loadbalancer.server.port=2202"
      # Admin
      - "traefik.http.routers.ubooquity-admin.service=ubooquity-admin"
      - 'traefik.http.routers.ubooquity-admin.rule=Host("ubooquity-admin.$DOMAIN")'
      - "traefik.http.routers.ubooquity-admin.tls=true"
      - "traefik.http.routers.ubooquity-admin.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.ubooquity-admin.entrypoints=websecure"
      - "traefik.http.services.ubooquity-admin.loadbalancer.server.port=2203"
    networks:
      - web_proxy

networks:
  web_proxy:
    external:
      name: web_proxy