version: "3.9"

services:
  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - ${SYNCTHING_BASE_FOLDER}:/mnt/syncthing
    ports:
      - 22000:22000
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing.service=syncthing"
      - "traefik.http.routers.syncthing.tls=true"
      - "traefik.http.routers.syncthing.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.syncthing.entrypoints=websecure"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
      - "traefik.http.routers.syncthing.middlewares=authelia@docker"
    networks:
      - web_proxy

networks:
  web_proxy:
    external: true
