version: "3.9"

services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.21@sha256:f104ee51e5124d83cf3be9b37480649355d223f7d8f9e453d0d5ef06c6e3b31b
    container_name: flaresolverr
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    networks:
      - torrent
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8191"]
      start_period: 20s
      interval: 30s
      timeout: 5s
      retries: 5

networks:
  torrent:
    external: true
