version: "3.9"

services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.6@sha256:07abf069637a3a2d94b82d4074bb61237ecfe62536ac8f6fc4664fd98329f7c4
    container_name: flaresolverr
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    networks:
      - web_proxy

networks:
  web_proxy:
    external: true
