version: "3.9"

services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.4.3@sha256:057eedf25a22905685c55be78b2dd70bcd617a921384cd17cb3f4e8901753331
    container_name: flaresolverr
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    networks:
      - torrent
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8191"]
      start_period: 20s
      interval: 30s
      timeout: 5s
      retries: 5

networks:
  torrent:
    external: true
