version: "3.9"

services:
  photoprism:
    container_name: photoprism
    image: photoprism/photoprism:latest
    depends_on: 
      - photoprism_db
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      - PHOTOPRISM_ADMIN_PASSWORD=${PHOTOPRISM_ADMIN_PASSWORD}
      - PHOTOPRISM_DEBUG=false
      - PHOTOPRISM_PUBLIC=false
      - PHOTOPRISM_READONLY=false
      - PHOTOPRISM_UPLOAD_NSFW=true
      - PHOTOPRISM_DETECT_NSFW=false
      - PHOTOPRISM_EXPERIMENTAL=false
      - PHOTOPRISM_SITE_URL=${PHOTOPRISM_SITE_URL}
      - PHOTOPRISM_SITE_TITLE=PhotoPrism
      - PHOTOPRISM_SITE_CAPTION=Browse Your Life
      - PHOTOPRISM_SITE_DESCRIPTION=Browse Your Life
      - PHOTOPRISM_SITE_AUTHOR=PhotoPrism
      - PHOTOPRISM_HTTP_HOST=0.0.0.0
      - PHOTOPRISM_HTTP_PORT=2342
      - PHOTOPRISM_SETTINGS_HIDDEN=false
      - PHOTOPRISM_DATABASE_DRIVER=mysql
      - PHOTOPRISM_DATABASE_DSN=photoprism:${PHOTOPRISM_DB_PASSWORD}@tcp(photoprism_db:3306)/photoprism?charset=utf8mb4,utf8&parseTime=true
      - PHOTOPRISM_SIDECAR_JSON=true
      - PHOTOPRISM_SIDECAR_YAML=true
      - PHOTOPRISM_THUMB_FILTER=lanczos
      - PHOTOPRISM_THUMB_UNCACHED=false
      - PHOTOPRISM_THUMB_SIZE=2048
      - PHOTOPRISM_THUMB_SIZE_UNCACHED=7680
      - PHOTOPRISM_JPEG_SIZE=7680
      - PHOTOPRISM_JPEG_QUALITY=92
      - PHOTOPRISM_DARKTABLE_PRESETS=false
      - UID=${PUID}
      - GID=${PGID}
    volumes:
      - ./config:/photoprism/storage
      - ./pictures:/photoprism/originals
      - ./import:/photoprism/import
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.photoprism.service=photoprism"
      - "traefik.http.routers.photoprism.tls=true"
      - "traefik.http.routers.photoprism.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.photoprism.entrypoints=websecure"
      - "traefik.http.services.photoprism.loadbalancer.server.port=2342"
      - "traefik.http.routers.photoprism.middlewares=authelia@docker"
    networks:
      - web_proxy
      - db

  photoprism_db:
    image: linuxserver/mariadb:version-110.4.16mariabionic
    container_name: photoprism_db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${PHOTOPRISM_DB_ROOT_PASSWORD}
      - MYSQL_USER=photoprism
      - MYSQL_PASSWORD=${PHOTOPRISM_DB_PASSWORD}
      - MYSQL_DATABASE=photoprism
    volumes:
      - ./db:/config
    restart: unless-stopped
    networks:
      - db

  photoprism_db_dumper:
    image: paolobasso/database_dumper:latest
    restart: unless-stopped
    depends_on:
      - photoprism_db
    container_name: photoprism_db_dumper
    volumes:
      - ./dumps:/dumps
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DUMPER_TYPE=mysql
      - DUMPER_DATABASE=photoprism
      - DUMPER_HOST=photoprism_db
      - DUMPER_USER=photoprism
      - DUMPER_PASSWORD=${PHOTOPRISM_DB_PASSWORD}
      - DUMPER_HEALTHCHECKS_URL=${PHOTOPRISM_DB_DUMPER_HEALTHCHECKS_URL}
    networks:
      - db

networks:
  db:
    driver: bridge
  web_proxy:
    external:
      name: web_proxy