version: "3.9"

services:
  searxng_redis:
    container_name: searx_ngredis
    image: redis:6-alpine
    command: redis-server --save "" --appendonly "no"
    networks:
      - searxng
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    depends_on:
      - searxng_redis
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME}/
    volumes:
      - ./config:/etc/searxng:rw
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.searxng.service=searxng"
      - "traefik.http.routers.searxng.tls=true"
      - "traefik.http.routers.searxng.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.searxng.entrypoints=websecure"
      - "traefik.http.services.searxng.loadbalancer.server.port=8080"
      - "traefik.http.routers.searxng.middlewares=authelia@docker"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    networks:
      - web_proxy
      - searxng

networks:
  web_proxy:
    external: true
  searxng:
    driver: bridge
