version: "3.9"

services:
  monicahq_db:
    image: linuxserver/mariadb:10.5.13-alpine
    container_name: monicahq_db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MONICAHQ_DB_ROOT_PASSWORD}
      - MYSQL_USER=monicahq
      - MYSQL_PASSWORD=${MONICAHQ_DB_PASSWORD}
      - MYSQL_DATABASE=monicahq
    volumes:
      - ./db:/config
    restart: unless-stopped
    networks:
      - db

  monicahq_db_dumper:
    image: paolobasso/database_dumper:latest
    restart: unless-stopped
    depends_on:
      - monicahq_db
    container_name: monicahq_db_dumper
    volumes:
      - ./dumps:/dumps
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DUMPER_TYPE=mysql
      - DUMPER_DATABASE=monicahq
      - DUMPER_HOST=monicahq_db
      - DUMPER_USER=monicahq
      - DUMPER_PASSWORD=${MONICAHQ_DB_PASSWORD}
      - DUMPER_HEALTHCHECKS_URL=${MONICAHQ_DB_DUMPER_HEALTHCHECKS_URL}
    networks:
      - db

  monicahq:
    image: monica:3
    container_name: monicahq
    depends_on:
      - monicahq_db
    volumes:
      - ./storage:/var/www/html/storage
    environment:
      - TZ=${TZ}
      - APP_KEY=${MONICAHQ_APP_KEY}
      - DB_CONNECTION=mysql
      - DB_HOST=monicahq_db
      - DB_PORT=3306
      - DB_DATABASE=monicahq
      - DB_USERNAME=monicahq
      - DB_PASSWORD=${MONICAHQ_DB_PASSWORD}
      - MAIL_MAILER=${MONICAHQ_MAIL_MAILER}
      - MAIL_FROM_ADDRESS=${MONICAHQ_MAIL_FROM}
      - MAIL_HOST=${MONICAHQ_MAIL_HOST}
      - MAIL_PORT=${MONICAHQ_MAIL_PORT}
      - MAIL_USERNAME=${MONICAHQ_MAIL_USERNAME}
      - MAIL_PASSWORD=${MONICAHQ_MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${MONICAHQ_MAIL_ENCRYPTION}
      - ENABLE_GEOLOCATION=${MONICAHQ_ENABLE_GEOLOCATION}
      - LOCATION_IQ_API_KEY=${MONICAHQ_LOCATION_IQ_API_KEY}
      - ENABLE_WEATHER=${MONICAHQ_ENABLE_WEATHER}
      - DARKSKY_API_KEY=${MONICAHQ_DARKSKY_API_KEY}
      - APP_TRUSTED_PROXIES=*
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monicahq.service=monicahq"
      - "traefik.http.routers.monicahq.tls=true"
      - "traefik.http.routers.monicahq.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.monicahq.entrypoints=websecure"
      - "traefik.http.services.monicahq.loadbalancer.server.port=80"
      - "traefik.http.routers.monicahq.middlewares=authelia@docker"
    networks:
      - web_proxy
      - db

networks:
  web_proxy:
    external: true
  db:
    driver: bridge
