version: "3.9"

services:
  jellyseerr:
    image: docker.io/fallenbagel/jellyseerr:1.7.0@sha256:6dcdb5ba50913a14b2bd7df6388607ce175121f3416679c2746501256ac9f075
    container_name: jellyseerr
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.jellyseerr.loadbalancer.server.port=5055"
      - "traefik.http.routers.jellyseerr.service=jellyseerr"
      - "traefik.http.routers.jellyseerr.tls=true"
      - "traefik.http.routers.jellyseerr.entrypoints=websecure"
      - 'traefik.http.routers.jellyseerr.rule=Host("$JELLYSEERR_HOST")'
    # - "traefik.http.routers.jellyseerr.middlewares=authelia@docker"
    networks:
      - web_proxy
      - torrent

networks:
  web_proxy:
    external: true
  torrent:
    external: true
